export const FETCH_RESTAURANTS = 'FETCH_RESTAURANTS';
export const NEW_ITEM_ADDED = 'NEW_MENU_ITEM_ADDED';
export const FETCH_NEW_ITEMS = 'FETCH_NEW_ITEMS';
export const SEND_NEW_ITEM_LIST = 'SEND_NEW_ITEM_LIST';