export const FETCH_RESTAURANTS = 'FETCH_RESTAURANTS';
export const FETCH_RESTAURANT_SEARCH_RESULTS = 'FETCH_RESTAURANT_SEARCH_RESULTS';
export const FETCH_RESTAURANT = 'FETCH_RESTAURANT';
export const FETCH_DISHES = 'FETCH_DISHES';
export const FETCH_DISH_SEARCH_RESULTS = 'FETCH_DISH_SEARCH_RESULTS';
export const FETCH_MY_RATINGS = 'FETCH_MY_RATINGS';
